---
language: python
python: "2.7"
sudo: required

addons:
  apt:
    packages:
      - php5-cli
      - php5-fpm
      - php5-curl
      - nginx

install:
  - "pip install ansible --upgrade"
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-galaxy carlosbuenosvinos.ansistrano-deploy carlosbuenosvinos.ansistrano-rollback --force"
  - "ln -s `pwd` ../kpeu3i.ansifony"

script:
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml"