---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - php5-curl

install:
  - "pip install ansible --upgrade"
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-galaxy install carlosbuenosvinos.ansistrano-deploy --force"
  - "ln -s `pwd` ../kpeu3i.ansifony"

script:
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ANSIBLE_CONFIG=tests/ansible.cfg ansible-playbook -i tests/inventory tests/test.yml"