---
language: python
python: "2.7"
sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - php5-curl

install:
  - pip install ansible --upgrade
  - ansible-galaxy install carlosbuenosvinos.ansistrano-deploy --force

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test.yml"