---
- name: "Assests: symlink/install assets"
  shell: chdir={{ ansistrano_release_path.stdout }}
    export SYMFONY_ENV={{ ansifony_symfony_env }} && {{ ansifony_php_path }} {{ ansifony_symfony_console_command }} assets:install --symlink --no-debug
  when: ansifony_assets_install

- name: "Assests: dump"
  shell: chdir={{ ansistrano_release_path.stdout }}
    export SYMFONY_ENV={{ ansifony_symfony_env }} && {{ ansifony_php_path }} {{ ansifony_symfony_console_command }} assetic:dump --no-debug
  when: ansifony_assetic_dump
