---
- name: "php-fpm: restart"
  service: name=php5-fpm state=restarted
  sudo: yes
  sudo_user: "{{ ansifony_remote_user }}"
  when: ansifony_php5_fpm_restart

- name: "nginx: restart"
  service: name=nginx state=reloaded
  sudo: yes
  sudo_user: "{{ ansifony_remote_user }}"
  when: ansifony_nginx_restart